### PR TITLE
build(python): update supported Python versions: 3.9 - 3.13

### PR DESCRIPTION
**Pull request by noirbizarre**
This PR update this library supported Python versions to match officially supported Python versions aka. Python 3.9-3.13.

- CI & Tox file have been updated accordingly.
- Ruff target version has been updated to 3.9
- All files have been formatted to this target

Includes #34, so the PR will be rebased as soon as #34 is merged

### CODE REVIEW

**Review by felix-martel — APPROVED** [review]
LGTM! Sad to see Python 3.8 leave but a good decision indeed.

**Comment by felix-martel** [comment]
I'll try to fix and merge #34 tonight or during lunch. Stay tuned!

**Comment by felix-martel** [comment]
@noirbizarre #34 has been merged

**Comment by noirbizarre** [comment]
There it is: PR updated 👍🏼

**Comment by noirbizarre** [comment]
PR updated to solve lock conflict

**Review by felix-martel — APPROVED** [review]

**Comment by felix-martel** [comment]
Hello, thanks a lot for this! Sorry for the delay :(

**Pull request merged**
